import { useState } from 'react';
import { InputText } from 'soadtech-ui';

function heading(text: string) {
  return (
    <h3
      style={{
        fontSize: 'var(--st-font-size-lg)',
        fontWeight: 'var(--st-font-weight-medium)',
        marginBottom: 'var(--st-space-3)',
        color: 'var(--st-color-muted)',
      }}
    >
      {text}
    </h3>
  );
}

export function InputTextSection() {
  const [controlled, setControlled] = useState('');
  const [clearable, setClearable] = useState('Some text');

  return (
    <section style={{ marginBottom: 'var(--st-space-12)' }}>
      <h2
        style={{
          fontSize: 'var(--st-font-size-2xl)',
          fontWeight: 'var(--st-font-weight-semibold)',
          marginBottom: 'var(--st-space-6)',
        }}
      >
        InputText
      </h2>

      {/* States — Large */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('States — Large')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputText
            label="Rest"
            placeholder="Placeholder text"
            helperText="Helper text to complete the field"
          />
          <InputText
            label="Filled"
            defaultValue="Filled value"
            helperText="Helper text to complete the field"
          />
          <InputText
            label="Disabled"
            defaultValue="Disabled value"
            disabled
            helperText="Helper text to complete the field"
          />
          <InputText
            label="Required"
            placeholder="Required field"
            required
            helperText="This field is required"
          />
        </div>
      </div>

      {/* States — Medium */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('States — Medium')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputText
            size="md"
            label="Rest"
            placeholder="Placeholder text"
            helperText="Helper text"
          />
          <InputText
            size="md"
            label="Filled"
            defaultValue="Filled value"
            helperText="Helper text"
          />
          <InputText
            size="md"
            label="Disabled"
            defaultValue="Disabled value"
            disabled
            helperText="Helper text"
          />
        </div>
      </div>

      {/* Feedback */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('Feedback')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputText
            label="Success"
            defaultValue="Valid input"
            feedback={{ status: 'success', message: 'Looks good!' }}
          />
          <InputText
            label="Error"
            defaultValue="Invalid input"
            feedback={{ status: 'error', message: 'This field is required' }}
          />
          <InputText
            label="Warning"
            defaultValue="Risky value"
            feedback={{
              status: 'warning',
              message: 'This might cause issues',
            }}
          />
          <InputText
            label="AI"
            defaultValue="AI generated text"
            feedback={{
              status: 'ai',
              message: 'Generated by AI',
            }}
          />
        </div>
      </div>

      {/* Clearable */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('Clearable')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputText
            label="Clearable (controlled)"
            value={clearable}
            onChange={(e) => setClearable(e.target.value)}
            clearable
            onClear={() => setClearable('')}
            helperText="Click X to clear"
          />
          <InputText
            label="Clearable (uncontrolled)"
            defaultValue="Clear me"
            clearable
            helperText="Click X to clear"
          />
        </div>
      </div>

      {/* Counter */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('Counter')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputText
            label="With maxLength"
            placeholder="Type something..."
            maxLength={100}
            helperText="Max 100 characters"
          />
          <InputText
            label="Controlled + counter"
            value={controlled}
            onChange={(e) => setControlled(e.target.value)}
            maxLength={50}
          />
        </div>
      </div>

      {/* Password */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('Password')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputText
            label="Password"
            type="password"
            placeholder="Enter password"
            helperText="Must be 8+ characters"
          />
        </div>
      </div>

      {/* With description */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('With description')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputText
            label="Email"
            description="We'll never share your email"
            placeholder="name@example.com"
            type="email"
          />
        </div>
      </div>

      {/* Left / Right elements */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('Left / Right elements')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputText
            label="With left element"
            placeholder="Search..."
            leftElement={
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                style={{ color: 'var(--st-color-muted)' }}
              >
                <circle
                  cx="7"
                  cy="7"
                  r="4.5"
                  stroke="currentColor"
                  strokeWidth="1.2"
                />
                <path
                  d="M10.5 10.5L14 14"
                  stroke="currentColor"
                  strokeWidth="1.2"
                  strokeLinecap="round"
                />
              </svg>
            }
          />
          <InputText
            label="With right element"
            placeholder="0.00"
            rightElement={
              <span
                style={{
                  fontSize: 'var(--st-font-size-sm)',
                  color: 'var(--st-color-muted)',
                }}
              >
                USD
              </span>
            }
          />
          <InputText
            label="Both elements"
            placeholder="Enter amount"
            leftElement={
              <span
                style={{
                  fontSize: 'var(--st-font-size-sm)',
                  color: 'var(--st-color-muted)',
                }}
              >
                $
              </span>
            }
            rightElement={
              <span
                style={{
                  fontSize: 'var(--st-font-size-sm)',
                  color: 'var(--st-color-muted)',
                }}
              >
                .00
              </span>
            }
            clearable
          />
        </div>
      </div>
    </section>
  );
}
