import { useState } from 'react';
import { InputTextArea } from 'soadtech-ui';

function heading(text: string) {
  return (
    <h3
      style={{
        fontSize: 'var(--st-font-size-lg)',
        fontWeight: 'var(--st-font-weight-medium)',
        marginBottom: 'var(--st-space-3)',
        color: 'var(--st-color-muted)',
      }}
    >
      {text}
    </h3>
  );
}

function ToolbarButtons() {
  const btnStyle: React.CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    border: 'none',
    background: 'transparent',
    borderRadius: 'var(--st-radius-md)',
    color: 'var(--st-color-foreground)',
    cursor: 'pointer',
    fontSize: 'var(--st-font-size-sm)',
    fontWeight: 'var(--st-font-weight-semibold)',
    padding: 0,
  };

  return (
    <>
      <button type="button" style={btnStyle}>
        B
      </button>
      <button type="button" style={{ ...btnStyle, fontStyle: 'italic' }}>
        I
      </button>
      <button
        type="button"
        style={{ ...btnStyle, textDecoration: 'underline' }}
      >
        U
      </button>
      <span
        style={{
          width: 1,
          height: 16,
          background: 'var(--st-color-border)',
          margin: '0 var(--st-space-1)',
        }}
      />
      <button type="button" style={btnStyle}>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path
            d="M2 4h12M2 8h8M2 12h12"
            stroke="currentColor"
            strokeWidth="1.2"
            strokeLinecap="round"
          />
        </svg>
      </button>
      <button type="button" style={btnStyle}>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path
            d="M2 4h12M4 8h8M2 12h12"
            stroke="currentColor"
            strokeWidth="1.2"
            strokeLinecap="round"
          />
        </svg>
      </button>
    </>
  );
}

export function InputTextAreaSection() {
  const [controlled, setControlled] = useState('');

  return (
    <section style={{ marginBottom: 'var(--st-space-12)' }}>
      <h2
        style={{
          fontSize: 'var(--st-font-size-2xl)',
          fontWeight: 'var(--st-font-weight-semibold)',
          marginBottom: 'var(--st-space-6)',
        }}
      >
        InputTextArea
      </h2>

      {/* Default states */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('Default States')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputTextArea
            label="Rest"
            placeholder="Placeholder text"
            maxLength={100}
          />
          <InputTextArea
            label="Filled"
            defaultValue="Some filled content"
            maxLength={100}
          />
          <InputTextArea
            label="Disabled"
            defaultValue="Disabled content"
            disabled
            maxLength={100}
          />
          <InputTextArea
            label="Required"
            placeholder="Required field"
            required
            maxLength={100}
          />
        </div>
      </div>

      {/* Feedback */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('Feedback')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputTextArea
            label="Error"
            defaultValue="Invalid input"
            maxLength={100}
            feedback={{ status: 'error', message: 'This field is required' }}
          />
          <InputTextArea
            label="AI"
            defaultValue="AI generated text"
            maxLength={100}
            feedback={{ status: 'ai', message: 'Generated by AI' }}
          />
          <InputTextArea
            label="Success"
            defaultValue="Valid input"
            maxLength={100}
            feedback={{ status: 'success', message: 'Looks good!' }}
          />
          <InputTextArea
            label="Warning"
            defaultValue="Risky value"
            maxLength={100}
            feedback={{
              status: 'warning',
              message: 'This might cause issues',
            }}
          />
        </div>
      </div>

      {/* Toolbar variant */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('With Toolbar')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputTextArea
            label="Toolbar — Rest"
            placeholder="Start typing..."
            maxLength={100}
            toolbar={<ToolbarButtons />}
          />
          <InputTextArea
            label="Toolbar — Error"
            defaultValue="Invalid content"
            maxLength={100}
            toolbar={<ToolbarButtons />}
            feedback={{ status: 'error', message: 'Content is too short' }}
          />
          <InputTextArea
            label="Toolbar — Disabled"
            defaultValue="Disabled content"
            maxLength={100}
            toolbar={<ToolbarButtons />}
            disabled
          />
        </div>
      </div>

      {/* Controlled with counter */}
      <div style={{ marginBottom: 'var(--st-space-8)' }}>
        {heading('Controlled + Counter')}
        <div
          style={{
            display: 'flex',
            gap: 'var(--st-space-6)',
            flexWrap: 'wrap',
            alignItems: 'start',
          }}
        >
          <InputTextArea
            label="Controlled"
            value={controlled}
            onChange={(e) => setControlled(e.target.value)}
            maxLength={100}
            placeholder="Type to see counter update..."
          />
        </div>
      </div>
    </section>
  );
}
